// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj6am5cXUZPInyRqM5QbyZPVDFYg5BcAQ',
    appId: '1:716836618918:web:214f40849cc20dc4282a67',
    messagingSenderId: '716836618918',
    projectId: 'ai-interview-7333f',
    authDomain: 'ai-interview-7333f.firebaseapp.com',
    storageBucket: 'ai-interview-7333f.firebasestorage.app',
    measurementId: 'G-YFXTKT3YYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe40LX5offZfZRi6SswREoJVjD0Op2Juw',
    appId: '1:716836618918:android:cab0a5cfd7f49f44282a67',
    messagingSenderId: '716836618918',
    projectId: 'ai-interview-7333f',
    storageBucket: 'ai-interview-7333f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTNSawfT0O_k88dCah8ZstZF5siyjC6KU',
    appId: '1:716836618918:ios:e79fd4abdc4dbcf4282a67',
    messagingSenderId: '716836618918',
    projectId: 'ai-interview-7333f',
    storageBucket: 'ai-interview-7333f.firebasestorage.app',
    iosBundleId: 'com.example.ainterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTNSawfT0O_k88dCah8ZstZF5siyjC6KU',
    appId: '1:716836618918:ios:e79fd4abdc4dbcf4282a67',
    messagingSenderId: '716836618918',
    projectId: 'ai-interview-7333f',
    storageBucket: 'ai-interview-7333f.firebasestorage.app',
    iosBundleId: 'com.example.ainterview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj6am5cXUZPInyRqM5QbyZPVDFYg5BcAQ',
    appId: '1:716836618918:web:0bd4b69fef97b9cf282a67',
    messagingSenderId: '716836618918',
    projectId: 'ai-interview-7333f',
    authDomain: 'ai-interview-7333f.firebaseapp.com',
    storageBucket: 'ai-interview-7333f.firebasestorage.app',
    measurementId: 'G-SV39JZ6QVR',
  );
}
